site: 'My Vast, Right-Wing Conspiracy'
url: 'https://coach-punk.github.io'
title:
  - MVRWC
description: Simple and minimalistic conspiracy theorist.
twitter:
  username: 2oft
  card: The most amazing Twitter ever
  creator: John
author:
  twitter: 2oft
  name: John Stansbury
  avatar: null
  email: null
  url: 'https://mvrwc.com'
permalink: pretty
baseurl: ''
highlighter: none
exclude:
  - .jekyll-cache
compress_html:
  clippings: all
  comments:
    - '<!-- '
    - ' -->'
sass:
  sass_dir: _sass
  style: ':compressed'
theme: null
plugins:
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate-v2
  - jekyll-admin
collections:
  pages:
    output: true
    permalink: '/:name'
  posts:
    output: true
    permalink: '/:year/:month/:day/:slug'
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      layout: post
