var date    = new Date().getDate();
var quote   = new Array();
 quote[1]   = "The joys of John’s life include punching things, peanut butter, and stealing things from the internet.";
 quote[2]   = "A big pet peeve of John’s is terrible grammer, widdowed text, and misspellings. Oh, and gigantic gaps vertically in text from justified text.";
 quote[3]   = "Never happier than when he gets some smack in an upright position, ready for laying down.";
 quote[4]   = "Not as random as he would lead you to believe.";
 quote[5]   = "Never thrown from a horse, a bar, or a job. Well, the one time, but that job wasn’t fun at all."; 
 quote[6]   = "John loves the witty repartee, and posts funny stuff on Twitter (when it isn’t faceplanting).";
 quote[7]   = "John has never been referred to as ‘bootilicous’";
 quote[8]   = "He fears the swimming. And the water. And the drowning. And the clean.";
 quote[9]   = "John believes a clean floor is always covered with a thin layer of dirty clothing, ready for women–folk to clean.";
 quote[10]  = "The rumors are true.";
 quote[11]  = "John would love to treat you better, but he can barely keep his javascript valid, let alone buy you nice things.";
 quote[12]  = "John forgot to put something witty here. Hopefully somebody is paying attention, and will tell him to be more funnier.";
 quote[13]  = "Be kind and avoid mentioning or pointing out Valentine’s Day. Just...don’t mention it. Please.";
 quote[14]  = "As a full–time loser bum, he wouldn’t really say he <em>misses</em> work, much like women say they don’t miss labor.";
 quote[15]  = "John finally figured out the PHP includes thing. Joyent is excused.";
 quote[16]  = "John does not, in fact, fear monkeys. Do not believe everything you read on the internet.";
 quote[17]  = "Go ahead, <a href=\"http://www.uniqlo.jp/uniqlock/\">click this</a>";
 quote[18]  = "While he may make reference to it, his kung-fu is not really that much better than yours. You have good kung-fu, really.";
 quote[19]  = "Aaaaaaaaaaaaaye soooooooooooo ruuuuuuule !!!!!!!!!!";
 quote[20]  = "Boxers. Because you were dying to know.";
 quote[21]  = "Remember a few days ago, about the horse and the bar and stuff? He was totally being serious, you guys. No, really! No, shut up! I mean it! I am like, totally serial!";
 quote[22]  = "John was in touch with his feminine side. Until the authorities arrived, anyway. I probably will regret admitting that. Er, he will...";
 quote[23]  = "Not a swimmer.";
 quote[24]  = "John was never offered the role of ‘Old Spice’ during the reunion tour, no matter what Matt Drudge reported. Lies, I tell you. Lies.";
 quote[25]  = "More of a shag carpet kind of guy.";
 quote[26]  = "Plays several musical instruments, include guitar, drums, and that thing you press the buttons on and it makes the fat beets. Like, a zither, or something.";
 quote[27]  = "The boy likes him some juicy steak. Mmm...steak...";
 quote[28]  = "He is neither lucky with the ladies nor cards.";
 quote[29]  = "At some point in the past, after terse words were exchanged and a relationship damaged, and he no longer speaks to Madonna. While John was vehement in denial of any involvement with the creation of any of her children, he also claims to not care about said children. Only time will tell what this really means.";
 quote[30]  = "John used to love the blogs. Then he got off that crack pipe. He now has real friends and darker skin.";
 quote[31]  = "The monkeys. Just don’t bring it up. Trust me on this.";
 
document.write(quote[date]);
